gliff-ai/curate

.github/workflows/azure-static-web-apps-salmon-meadow-05ee3f103.yml, package-lock.json
Same as https://github.com/gliff-ai/annotate/pull/123
Does dependabot, skips deploys for it
=> Dependabot

.github/workflows/lint-build-test.yml, package-lock.json, package.json, src/MetadataDrawer.tsx, src/searchAndSort/SearchAndSortBar.tsx, src/ui.tsx
Use a map to allow display labels in the dropdown. it merges all found keys with all the labelled ones, and excludes any chosen. Not sure if it's working with sort tbh, but neither did the other one!
Feel free to steal bits, merge or whatever!
=> Pretty labels2

package.json
fixes `import Curate from '@gliff-ai/curate';`
=> fix: Module import

src/components/LabelsPopover.tsx, src/searchAndSort/LabelsFilterAccordion.tsx, src/searchAndSort/SearchAndSortBar.tsx, src/ui.tsx
addresses #49, part 1
No
No
No
=> feat: Image-wise labels

examples/src/index.tsx, src/components/Tile.tsx, src/searchAndSort/interfaces.ts, src/ui.tsx
Handle base64 thumbnails and use `saveImageCallback`. Needed with the new-gallery dominate PR.
relates #74
=> New gallery

package.json, src/ui.tsx
=> Launch annotate

.eslintrc.js, package-lock.json, src/helpers.ts, src/sort/SortPopover.tsx, src/ui.tsx
- Update svg loading so it's a function
- Fix the width of the sidebar and use flexbox to space the top buttons
- Lints
=> Minor changes

src/components/SizeThumbnails.tsx, src/ui.tsx
Move thumbnail logic into the component to make ui.tsx a little smaller
=> fix: move thumbnail sizing into component

src/components/FloatingButton.tsx, src/components/HtmlTooltip.tsx, src/components/SizeThumbnails.tsx, src/components/TooltipButton.tsx, src/searchAndSort/LabelsFilterAccordion.tsx, src/searchAndSort/SearchAndSortBar.tsx, src/sort/SortPopover.tsx, src/ui.tsx
We do an SVG wrapped in a button wrapped in a tooltip frequently, so now it's a component, as it the tooltip to remove a load of duplication.
=> Button component

src/MetadataDrawer.tsx, src/components/LabelsPopover.tsx, src/components/TooltipButton.tsx, src/searchAndSort/LabelsFilterAccordion.tsx, src/ui.tsx
fix upload image button and a few minor styling issues (see below).
No
No
No
=> fix: Miscellanea

src/MetadataDrawer.tsx, src/sort/SortPopover.tsx, src/ui.tsx
Adds:
- make curate compatible with the metadata passed by dominate.
closes gliff-ai/dominate/issues/165, gliff-ai/dominate/issues/166,
No
No
No
Have any database migrations been committed as part of this pull request?
=> fix: Metadata

package-lock.json, src/theme.ts
All the minor dependabots, scripted PR
=> Dependabot batch

src/searchAndSort/LabelsFilterAccordion.tsx, src/sort/GroupBySeparator.tsx, src/sort/SortPopover.tsx, src/sort/index.tsx, src/ui.tsx
addresses gliff-ai/curate/issues/117 (logic only)
No
No
No
=> feat: Sort and group by

package-lock.json, package.json
=> build: update gliff-ai STYLE

src/ui.tsx
This PR is part of gliff-ai/dominate/pull/275.
=> feat: Add prop trustedServiceButtonToolbar

examples/index.tsx, examples/samples/metadata.json, src/components/AssigneesDialog.tsx, src/components/Tooltips.ts, src/components/index.ts, src/ui.tsx
- owners can assign images to collaborators
- only owners can upload images
No
No
No
=> feat: Owners can assign images to collaborators

babel.config.json, jest.config.js, package-lock.json, package.json, src/MetadataDrawer.tsx, src/components/AssigneesDialog.tsx, src/components/AutoAssignDialog.test.tsx, src/components/AutoAssignDialog.tsx, src/components/LabelsPopover.tsx, src/helpers.ts, src/searchAndSort/LabelsFilterAccordion.tsx, src/sort/SortPopover.tsx, src/ui.tsx, tsconfig.json
Adds system tests for the automatic assignment of images to collaborators, using Jest and React Testing Library.
closes gliff-ai/curate/issues/241
addresses gliff-ai/curate/issues/243
Yes, see`package.json`.
=> test: AutoAssignDialog.tsx

.github/workflows/codeql-analysis.yml
=> ci: update codeQL to use TS

package-lock.json
All the minor dependabots, scripted PR
=> chore: dependabot batch

src/ui.tsx
=> fix: copy props.multiLabel into state.multiLabel

.github/workflows/lint-build-test.yml, package-lock.json, package.json, src/index.test.tsx
- Move Style, Upload and CSStype to peer deps
- Bump Upload to latest
=> feat: bump upload, tidy peer deps

package-lock.json, package.json, src/ui.tsx
Mixes RGB channels when creating thumbnails so they're no longer red.
=> fix: redness

src/MetadataDrawer.tsx, src/interfaces.ts, src/ui.tsx
Add a couple of fields in the Metadata type to tidy up a little.
There might be more we can add? And should these ones be optional?
=> fix: Update Meta interface

examples/samples/metadata.json, src/components/ViewAnnotationsDialog.tsx, src/interfaces.ts, src/search/SearchBar.tsx, src/ui.tsx
ViewAnnotationsDialog now lists all users who have made an annotation, be they collaborator, member or owner. Also fixes the title of the dialog to say "Compare Annotations" when the Compare Annotations button is clicked.
Requires https://github.com/gliff-ai/dominate/pull/753 to work
=> feat: List all annotations
