src/components/LeftDrawer.tsx, src/searchAndSort/LabelsAccordion.tsx
Adds:
- Double-click to select/deselect all labels but one (as in #31)
- Select/deselect all labels (buttons and hover info, as described in Josh's UI layout, see #38)
closes #31
No
No
No
=> feat: Select/deselect all (or all but one) labels

.npmignore, package.json, src/ui.tsx, tsconfig.json, webpack.build.js
Adds:
- make prop `metadata` optional and change Curate so that it loads without props
- add callback for saving uploaded images as props
part 1 of gliff-ai/dominate#94
No
No
No
=> feat: Add save uploaded images callback

.github/workflows/lint-build-test.yml, .npmignore, package.json
I removed `.npmignore` thinking it wasn't necessary, turns out it is (!), otherwise `.gitignore` prevails and the `/dist` folder is not included in the published npm package...
=> fix: Add .npmignore

src/searchAndSort/interfaces.ts
Adds `number` to allowed metadata types. Makes life a lot easier.
=> feat: add number to allowed metadata types

src/components/Tile.tsx, src/ui.tsx
Adds:
- select multiple thumbnails
- delete selected thumbnails
- scale images so they fit inside the canvas
Notes: 
- single click on thumbnail to select a single image
- double-click to open metadata drawer
- command/ctrl  + click to select multiple non-consecutive images
- shift + arrow left/right to select multiple consecutive images
- shift + click to select all images between the two clicked images
- esc to deselect all 
closes #87 
closes #88
No
No
No
=> feat: Select multiple thumbnails and delete

src/ui.tsx
Adds a `saveLabelsCallback` prop, calls it from `updateLabels`.
closes #49 
(will need to merge dominate PR for this to work of course)
=> feat: add saveLabelsCallback, and use it

.eslintrc.js, src/ui.tsx
As with Annotate, allow hiding the app bar so we can wrap it nicely
Moves "upload" to bottom right, typical of most Material Apps, likely as a temp measure until we get @joshuajames-smith thoughts.
Branched from and merging into @ChrisBaidoo 's branch
=> Hide app bar

package.json, webpack.build.js, webpack.package.js
Rename the webpack configs to clearly differentiate between building the example and packaging for npm.
Build uses a very verbose sourcemap and dev mode as it's published to staging.curate.gliff.app for our use only or served locally
Package still creates a source map and links to it (as it's open source, revealing the code isn't an issue), but also builds in prod mode so the code should be much smaller!
=> fix: name webpack files sensibly

examples/metadata.json, src/MetadataDrawer.tsx, src/theme.ts
Truncate metadata if it's too long
FIx #98 
When we refactor into a proper theme, we can have a "truncate" class which will make life better
=> Wrap Image Names etc

src/decorators/index.tsx, src/decorators/progress.tsx, src/ui.tsx
Add decorator to stop rendering a loading spinner as soon as curate mounts (works only when curate is loaded onto dominate).
gliff-ai/roadmap/issues/54, full-screen spinner for page load.
No
No
No
Have any database migrations been committed as part of this pull request?
=> feat: Full-screen spinner

src/MetadataDrawer.tsx, src/searchAndSort/SearchAndSortBar.tsx
At present all metadata keys not listed in`metadataNameMap` are excluded from the metadata section. 
I've changed `MetadataDrawer.tsx` so that all sensible matadata keys are displayed in the drawer, even if they miss an extended name.
No
No
No
No
=> fix: Hardcoded list of metadata keys

package-lock.json, package.json, src/components/LabelsPopover.tsx, src/components/Tooltips.ts, src/sort/SortPopover.tsx
replaced popovers in LabelsPopover.tsx and SortPopover.tsx with BasePopover.tsx.
relies on https://github.com/gliff-ai/style/pull/21
No
No
No
=> chore: Reuse BasePopover.tsx

src/ui.tsx
Add `plugins` prop to pass down to CURATE a button toolbar with all the plugins. Works only when CURATE is loaded onto DOMINATE.
No
No
No
=> feat: Add plugins prop

src/MetadataDrawer.tsx, src/searchAndSort/SearchAndSortBar.tsx, src/ui.tsx
Image items can differ in their metadata content, so sort and search should work with missing metadata key-value pairs.
How missing values are handled:
Metadata drawer: not displayed in the drawer.
Sort: replaced with a high number.
Search: excluded.
No
No
No
=> fix: Sort and search don't work with missing metadata keys

src/ui.tsx
This should make thumbnails invisible in logrocket.
=> data-private tag on Tile elements

package-lock.json, package.json
as it says on the tin - needed because of react-router-dom eslewhere
=> build: fix history

src/helpers.test.ts, src/helpers.ts, src/ui.tsx
- move method for filtering the metadata out of `ui.tsx`, so as to facilitate unit testing
- add unit test for `filterMetadata` function
no
=> test: Filter metadata

vite.config.lib.ts
It's a peer dep, but we still bundle it, which makes the lib _fat_ (and also means upstream we have multiple versions of upload loaded which we certainly don't want)
=> fix: remove upload from bundle

src/TableView.tsx, src/components/SizeThumbnails.tsx, src/helpers.ts, src/interfaces.ts, src/sort/SortPopover.tsx, src/ui.tsx
Minor datatable changes, addresses some of https://github.com/gliff-ai/curate/issues/417 (which i only saw after doing them...it doesn't aim to solve all the points in that issue, just some of the easy wins/obviously broken parts)
- It now works with sort/filter on the side bar (and removes those options from the columns)
- Add some small typings
- Move DataTable into new file to make ui.tsx very slightly neater
- Hide 'multiselect' button when on table view
- Disable thumbnail size on table view
- minor polish on sort popover
One thing that _isn't_ supported in DataTable is groupBy unless we give MUI the dollars. Not sure if we need a way in the UI to indicate that @joshuajames-smith ? 
Created 2 follow on issues:
https://github.com/gliff-ai/curate/issues/423 …
=> feat: nicer datatable

src/MetadataDrawer.tsx, src/TableView.tsx, src/TileView.tsx, src/components/AutoAssignDialog.tsx, src/components/Tile.tsx, src/components/index.ts, src/helpers.test.ts, src/helpers.ts, src/interfaces.ts, src/search/SearchBar.tsx, src/sort/GroupBySeparator.tsx, src/ui.tsx
- Move TileView out of UI.tsx into a new file, to match TableView
- Move the image selection state into UI, and then pass the value and an update function into both views, so they're in sync and work with our external sort and filter.
- It's now a Set rather than an array as then me don't need ot do as much management of duplicates etc
- It's a reducer, if Ui.tsx was functional, it's an easy swap to `useReducer` hook.
- `assigneesLenght` -> `assigneesLength` everywhere 😀 
- Add `filterShow` to MetaItems to replace `selected` as selected means "highlighted" throughout now
-  `thumbnailWidth`. `thumbnailHeight` are now just one state value as thumbnails are square
- TileView and TableView only receive the _filtered and sorted_ metadata now, I don't think they care about the full set? (maybe …
=> feat: Centralise selection state to share between Tile/Grid view

src/ui.tsx
Fixes the crash that happens when deleting an image. Was happening because `this.state.selectedImagesUid` wasn't updating when images were deleted, so it was still trying to find a selected image that no longer existed, getting `undefined` from `find`, and passing that into `MetadataDrawer`. Rather than deselect the image when the callback is fired, which still allows the crash to happen if for some reason the user re-selects the image before it disappears, I've gone with updating `selectedImagesUid` in `componentDidUpdate` when the props change.
=> fix: deselect deleted images on props update

src/components/Tooltips.ts, src/components/ViewAnnotationsDialog.tsx, src/ui.tsx
Adds the second username box in ViewAnnotationsDialog, and passes the second username to `annotateCallback`. The second username box has "Nobody" as its default value, which will launch ANNOTATE in single image readonly mode if left unchanged.
=> feat: second username box in ViewAnnotationsDialog
